language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
  - cl -e '(ql:quickload :cffi-grovel)
           (ql:quickload :shcl)
           (ql:quickload :shcl-test)
           (asdf:test-system :shcl-test)
           (if (shcl-test/report:*last-test-passed*)
               (uiop:quit 0)
               (uiop:quit 1))'
